#!/usr/bin/env python3
"""
AXIS Final State Fix
Deletes any 0020 migration and creates a state-only migration to mark fields as existing.
Run: python3 final_state_fix.py
"""

import os
import sys
import shutil
import re
import subprocess

MIGRATIONS_DIR = "axis_saas/migrations"

def delete_migration_0020():
    """Remove any 0020 migration file."""
    deleted = False
    for f in os.listdir(MIGRATIONS_DIR):
        if f.startswith("0020_") and f.endswith(".py"):
            filepath = os.path.join(MIGRATIONS_DIR, f)
            os.remove(filepath)
            print(f"✅ Deleted: {f}")
            deleted = True
            # Also delete __pycache__
            pycache = os.path.join(MIGRATIONS_DIR, "__pycache__")
            if os.path.exists(pycache):
                shutil.rmtree(pycache, ignore_errors=True)
                print("✅ Cleared __pycache__")
    if not deleted:
        print("ℹ️ No 0020 migration found to delete.")

def create_state_migration():
    """Create a new 0020 migration that only updates state."""
    content = '''# Generated by AXIS state fix
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0019_remove_feerecord_late_fee_accrued_and_more'),
    ]

    state_operations = [
        migrations.AddField(
            model_name='feerecord',
            name='due_date_offset',
            field=models.PositiveSmallIntegerField(default=15, help_text='Days after generation when fee is due'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Late fee amount applied per day', max_digits=6),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='automation_enabled',
            field=models.BooleanField(default=False, help_text='Enable monthly auto‑generation of fees'),
        ),
        migrations.AddField(
            model_name='student',
            name='automation_enabled',
            field=models.BooleanField(default=False, help_text='Enable monthly auto‑generation of fees'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations, database_operations=[])
    ]
'''
    filepath = os.path.join(MIGRATIONS_DIR, "0020_state_fix.py")
    with open(filepath, "w") as f:
        f.write(content)
    print(f"✅ Created state-only migration: {filepath}")

def run_migrations():
    """Run migrate to apply the state change."""
    print("\n🔄 Running `python manage.py migrate` to apply state fix...")
    try:
        subprocess.run([sys.executable, "manage.py", "migrate"], check=True)
        print("✅ Migrations applied successfully.")
    except subprocess.CalledProcessError as e:
        print(f"❌ Error running migrate: {e}")
        sys.exit(1)

def main():
    print("🛠️  AXIS Final State Fix")
    print("========================")
    if not os.path.exists(MIGRATIONS_DIR):
        print("❌ Migrations directory not found. Are you in the project root?")
        sys.exit(1)

    delete_migration_0020()
    create_state_migration()
    run_migrations()

    print("\n🎯 Done. The migration state is now in sync with the database.")
    print("You can now create new tenants without duplicate column errors.")

if __name__ == "__main__":
    main()
