#!/usr/bin/env python3
"""
Create migration to drop late_fee_accrued column from all tenant schemas.
Run this once to fix the NOT NULL violation.
"""

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
MIGRATION_FILE = PROJECT_ROOT / "axis_saas" / "migrations" / "0024_drop_late_fee_accrued.py"

MIGRATION_CONTENT = '''# Generated by patcher – drop late_fee_accrued column
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0023_notification'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'axis_saas_feerecord'
                        AND column_name = 'late_fee_accrued'
                    ) THEN
                        ALTER TABLE axis_saas_feerecord DROP COLUMN late_fee_accrued;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE axis_saas_feerecord ADD COLUMN late_fee_accrued numeric(10,2) DEFAULT 0.00 NOT NULL;"
        ),
    ]
'''

def main():
    # Write migration
    with open(MIGRATION_FILE, 'w') as f:
        f.write(MIGRATION_CONTENT)
    print(f"✅ Created migration: {MIGRATION_FILE}")

    # Run migrate
    print("\n🚀 Applying migration...")
    os.chdir(PROJECT_ROOT)
    python = sys.executable
    # If inside venv, use that python; else try venv/bin/python3
    if 'venv' not in python and 'venv' not in str(PROJECT_ROOT):
        venv_python = PROJECT_ROOT / "venv" / "bin" / "python3"
        if venv_python.exists():
            python = str(venv_python)
    cmd = f"{python} manage.py migrate"
    print(f"Running: {cmd}")
    os.system(cmd)
    print("\n✅ Done! The column `late_fee_accrued` has been dropped from all tenant schemas.")
    print("   Now you can run `python manage.py auto_generate_fees` without errors.")

if __name__ == "__main__":
    main()
