# Generated by Django 6.0.5 on 2026-06-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0006_gymattendance_duration_minutes_gymcustomer_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymsubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
