# Generated by Django 4.2.16 on 2026-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0008_stock_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclient",
            name="enabled_features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Select the school modules enabled for this tenant.",
            ),
        ),
    ]
