# Generated by AXIS state fix
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0019_remove_feerecord_late_fee_accrued_and_more'),
    ]

    state_operations = [
        migrations.AddField(
            model_name='feerecord',
            name='due_date_offset',
            field=models.PositiveSmallIntegerField(default=15, help_text='Days after generation when fee is due'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Late fee amount applied per day', max_digits=6),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='automation_enabled',
            field=models.BooleanField(default=False, help_text='Enable monthly auto‑generation of fees'),
        ),
        migrations.AddField(
            model_name='student',
            name='automation_enabled',
            field=models.BooleanField(default=False, help_text='Enable monthly auto‑generation of fees'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations, database_operations=[])
    ]
