# Generated by Django 6.0.5 on 2026-06-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0020_state_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_existing', models.PositiveIntegerField(default=0)),
                ('skipped_no_fee', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
