# Generated by remove_late_fee_wrong_models
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0026_add_late_fee_accrued'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'axis_saas_paymenttransaction'
                        AND column_name = 'late_fee_accrued'
                    ) THEN
                        ALTER TABLE axis_saas_paymenttransaction DROP COLUMN late_fee_accrued;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE axis_saas_paymenttransaction ADD COLUMN late_fee_accrued numeric(10,2) DEFAULT 0.00 NOT NULL;"
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'axis_saas_gympayment'
                        AND column_name = 'late_fee_accrued'
                    ) THEN
                        ALTER TABLE axis_saas_gympayment DROP COLUMN late_fee_accrued;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE axis_saas_gympayment ADD COLUMN late_fee_accrued numeric(10,2) DEFAULT 0.00 NOT NULL;"
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'axis_saas_gymsubscription'
                        AND column_name = 'late_fee_accrued'
                    ) THEN
                        ALTER TABLE axis_saas_gymsubscription DROP COLUMN late_fee_accrued;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE axis_saas_gymsubscription ADD COLUMN late_fee_accrued numeric(10,2) DEFAULT 0.00 NOT NULL;"
        ),
    ]
