# Generated by Django 6.0.5 on 2026-05-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0002_alter_student_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=150),
        ),
    ]
