# Generated by patch 02 - Gym extension
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0003_alter_student_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclient',
            name='tenant_type',
            field=models.CharField(choices=[('school', 'School'), ('gym', 'Gym')], default='school', max_length=20),
        ),
        migrations.CreateModel(
            name='GymCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gym_customers/')),
                ('membership_start', models.DateField(default=django.utils.timezone.now)),
                ('membership_end', models.DateField(blank=True, null=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_monthly_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('subscription_generation_day', models.PositiveSmallIntegerField(default=1)),
                ('due_date_offset', models.PositiveSmallIntegerField(default=15)),
                ('late_fee_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gym Settings',
            },
        ),
        migrations.CreateModel(
            name='GymSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='axis_saas.gymcustomer')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('customer', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='GymPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online')], default='cash', max_length=20)),
                ('payment_type', models.CharField(default='full', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='axis_saas.gymcustomer')),
                ('subscriptions', models.ManyToManyField(related_name='payments', to='axis_saas.gymsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='GymAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='axis_saas.gymcustomer')),
            ],
            options={
                'ordering': ['-date', '-check_in'],
                'unique_together': {('customer', 'date')},
            },
        ),
    ]
