# Generated by Django 4.2.16 on 2026-06-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0014_schoolfeesettings_default_extra_charges"),
    ]

    operations = [
            migrations.RunSQL('ALTER TABLE axis_saas_feerecord ADD COLUMN IF NOT EXISTS due_date_offset integer DEFAULT 15 NOT NULL;', reverse_sql=''),
    ]
