# Generated by Django 6.0.5 on 2026-07-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0027_drop_late_fee_from_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='late_fee_accrued',
        ),
        migrations.RemoveField(
            model_name='schoolclient',
            name='admin_password_hash',
        ),
    ]
