# Generated by Django 6.0.5 on 2026-07-27 06:52

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = []

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, unique=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_username', models.CharField(default='admin_pending', max_length=150)),
                ('admin_password', models.CharField(default='AxisFallback123!', max_length=128)),
                ('school_logo', models.FileField(blank=True, null=True, upload_to='school_logos/')),
                ('tenant_type', models.CharField(choices=[('school', 'School'), ('gym', 'Gym')], default='school', max_length=20)),
                ('enabled_features', models.JSONField(blank=True, default=list, help_text='Select the school modules enabled for this tenant.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_generation_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month (1-31)')),
                ('due_date_offset', models.PositiveSmallIntegerField(default=15, help_text='Days after generation when fee is due')),
                ('late_fee_penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty %', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fee Settings',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('father_cnic', models.CharField(help_text='35202-XXXXXXX-X', max_length=15)),
                ('parent_mobile', models.CharField(max_length=15)),
                ('grade', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('custom_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('enrolled_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='axis_saas.schoolclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online')], default='cash', max_length=20)),
                ('payment_type', models.CharField(default='full', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('fee_records', models.ManyToManyField(related_name='payments', to='axis_saas.feerecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='axis_saas.student')),
            ],
        ),
        migrations.AddField(
            model_name='feerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='axis_saas.student'),
        ),
        migrations.AlterUniqueTogether(
            name='feerecord',
            unique_together={('student', 'month', 'year')},
        ),
        migrations.CreateModel(
            name='GymCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gym_customers/')),
                ('membership_start', models.DateField(default=django.utils.timezone.now)),
                ('membership_end', models.DateField(blank=True, null=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_monthly_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('subscription_generation_day', models.PositiveSmallIntegerField(default=1)),
                ('due_date_offset', models.PositiveSmallIntegerField(default=15)),
                ('late_fee_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gym Settings',
            },
        ),
        migrations.CreateModel(
            name='GymSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='axis_saas.gymcustomer')),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('customer', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='GymPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online')], default='cash', max_length=20)),
                ('payment_type', models.CharField(default='full', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='axis_saas.gymcustomer')),
                ('subscriptions', models.ManyToManyField(related_name='payments', to='axis_saas.gymsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='GymAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='axis_saas.gymcustomer')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
            ],
            options={
                'ordering': ['-date', '-check_in'],
                'unique_together': {('customer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='axis_saas.productcategory')),
            ],
        ),
        migrations.RunSQL(
            sql='ALTER TABLE axis_saas_student DROP COLUMN IF EXISTS fee_custom_items CASCADE;',
            reverse_sql='ALTER TABLE axis_saas_student ADD COLUMN fee_custom_items JSONB NULL;',
        ),
        migrations.AddField(
            model_name='feerecord',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='gympayment',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='default_extra_charges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='default_extra_charges',
            field=models.JSONField(blank=True, default=list, help_text='Common charges used for future vouchers', null=True),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE axis_saas_feerecord ADD COLUMN IF NOT EXISTS due_date_offset integer DEFAULT 15 NOT NULL;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE axis_saas_feerecord ADD COLUMN IF NOT EXISTS late_fee_per_day numeric(6,2) DEFAULT 0.00 NOT NULL;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE axis_saas_schoolfeesettings ADD COLUMN IF NOT EXISTS automation_enabled boolean DEFAULT false NOT NULL;',
            reverse_sql='ALTER TABLE axis_saas_schoolfeesettings DROP COLUMN IF EXISTS automation_enabled;',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE axis_saas_student ADD COLUMN IF NOT EXISTS automation_enabled boolean DEFAULT false NOT NULL;',
            reverse_sql='ALTER TABLE axis_saas_student DROP COLUMN IF EXISTS automation_enabled;',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE axis_saas_feerecord ADD COLUMN IF NOT EXISTS due_date_offset integer DEFAULT 15 NOT NULL;',
            reverse_sql='ALTER TABLE axis_saas_feerecord DROP COLUMN IF EXISTS due_date_offset;',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE axis_saas_feerecord ADD COLUMN IF NOT EXISTS late_fee_per_day numeric(6,2) DEFAULT 0.00 NOT NULL;',
            reverse_sql='ALTER TABLE axis_saas_feerecord DROP COLUMN IF EXISTS late_fee_per_day;',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='feerecord',
                    name='due_date_offset',
                    field=models.PositiveSmallIntegerField(default=15, help_text='Days after generation when fee is due'),
                ),
                migrations.AddField(
                    model_name='feerecord',
                    name='late_fee_per_day',
                    field=models.DecimalField(decimal_places=2, default=0.0, help_text='Late fee amount applied per day', max_digits=6),
                ),
                migrations.AddField(
                    model_name='schoolfeesettings',
                    name='automation_enabled',
                    field=models.BooleanField(default=False, help_text='Enable monthly auto‑generation of fees'),
                ),
                migrations.AddField(
                    model_name='student',
                    name='automation_enabled',
                    field=models.BooleanField(default=False, help_text='Enable monthly auto‑generation of fees'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ManualGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_existing', models.PositiveIntegerField(default=0)),
                ('skipped_no_fee', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.CharField(blank=True, max_length=150, null=True)),
                ('log_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', help_text='Type of generation (manual or auto)', max_length=10)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunSQL(
            sql='ALTER TABLE axis_saas_feerecord DROP COLUMN IF EXISTS late_fee_accrued;',
            reverse_sql='ALTER TABLE axis_saas_feerecord ADD COLUMN late_fee_accrued numeric(10,2) DEFAULT 0.00 NOT NULL;',
        ),
        migrations.AddField(
            model_name='schoolclient',
            name='admin_password_hash',
            field=models.CharField(blank=True, help_text='Hashed password for admin login', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='late_fee_accrued',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Accumulated late fee amount', max_digits=10),
        ),
        migrations.RunSQL(
            sql="\n                DO $$\n                BEGIN\n                    IF EXISTS (\n                        SELECT 1 FROM information_schema.columns\n                        WHERE table_name = 'axis_saas_paymenttransaction'\n                        AND column_name = 'late_fee_accrued'\n                    ) THEN\n                        ALTER TABLE axis_saas_paymenttransaction DROP COLUMN late_fee_accrued;\n                    END IF;\n                END $$;\n            ",
            reverse_sql='ALTER TABLE axis_saas_paymenttransaction ADD COLUMN late_fee_accrued numeric(10,2) DEFAULT 0.00 NOT NULL;',
        ),
        migrations.RunSQL(
            sql="\n                DO $$\n                BEGIN\n                    IF EXISTS (\n                        SELECT 1 FROM information_schema.columns\n                        WHERE table_name = 'axis_saas_gympayment'\n                        AND column_name = 'late_fee_accrued'\n                    ) THEN\n                        ALTER TABLE axis_saas_gympayment DROP COLUMN late_fee_accrued;\n                    END IF;\n                END $$;\n            ",
            reverse_sql='ALTER TABLE axis_saas_gympayment ADD COLUMN late_fee_accrued numeric(10,2) DEFAULT 0.00 NOT NULL;',
        ),
        migrations.RunSQL(
            sql="\n                DO $$\n                BEGIN\n                    IF EXISTS (\n                        SELECT 1 FROM information_schema.columns\n                        WHERE table_name = 'axis_saas_gymsubscription'\n                        AND column_name = 'late_fee_accrued'\n                    ) THEN\n                        ALTER TABLE axis_saas_gymsubscription DROP COLUMN late_fee_accrued;\n                    END IF;\n                END $$;\n            ",
            reverse_sql='ALTER TABLE axis_saas_gymsubscription ADD COLUMN late_fee_accrued numeric(10,2) DEFAULT 0.00 NOT NULL;',
        ),
        migrations.RemoveField(
            model_name='feerecord',
            name='late_fee_accrued',
        ),
        migrations.RemoveField(
            model_name='schoolclient',
            name='admin_password_hash',
        ),
    ]
