# Generated by axis_patcher
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0004_schoolclass_class_teacher'),  # adjust to the last migration
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='axis_saas.schoolclass'),
        ),
    ]
