# Generated by Django 4.2.16 on 2026-08-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0005_add_school_class_to_student'),
    ]

    operations = [
    ]
