# Generated by Django 4.2.16 on 2026-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0015_feerecord_due_date_offset"),
    ]

    operations = [
            migrations.RunSQL('ALTER TABLE axis_saas_feerecord ADD COLUMN IF NOT EXISTS late_fee_per_day numeric(6,2) DEFAULT 0.00 NOT NULL;', reverse_sql=''),
    ]
