# Generated by Django 6.0.5 on 2026-06-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0016_feerecord_late_fee_per_day'),
    ]

    operations = [
    migrations.AddField(
        model_name='schoolfeesettings',
        name='automation_enabled',
        field=models.BooleanField(default=False, help_text='Enable monthly auto‑generation of fees'),
    ),
    migrations.AddField(
        model_name='student',
        name='automation_enabled',
        field=models.BooleanField(default=False, help_text='Enable monthly auto‑generation of fees'),
    ),
]
