# Generated by Django 6.0.5 on 2026-06-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0016_feerecord_late_fee_per_day'),
    ]

    
    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE axis_saas_schoolfeesettings ADD COLUMN IF NOT EXISTS automation_enabled boolean DEFAULT false NOT NULL;",
            reverse_sql="ALTER TABLE axis_saas_schoolfeesettings DROP COLUMN IF EXISTS automation_enabled;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE axis_saas_student ADD COLUMN IF NOT EXISTS automation_enabled boolean DEFAULT false NOT NULL;",
            reverse_sql="ALTER TABLE axis_saas_student DROP COLUMN IF EXISTS automation_enabled;"
        ),
    ]
    
