# Generated by Django 6.0.5 on 2026-06-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0016_feerecord_late_fee_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='due_date_offset',
            field=models.PositiveSmallIntegerField(default=15, help_text='Days after generation when fee is due'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Late fee amount applied per day', max_digits=6),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='automation_enabled',
            field=models.BooleanField(default=False, help_text='Enable monthly auto‑generation of fees'),
        ),
        migrations.AddField(
            model_name='student',
            name='automation_enabled',
            field=models.BooleanField(default=False, help_text='Enable monthly auto‑generation of fees'),
        ),
    ]
