# Generated by Django 6.0.5 on 2026-06-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0017_feerecord_due_date_offset_feerecord_late_fee_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='late_fee_accrued',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Accumulated late fee amount', max_digits=10),
        ),
    ]
