# Generated by fee_logs_patcher
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0021_manualgenerationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualgenerationlog',
            name='log_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', help_text='Type of generation (manual or auto)', max_length=10),
        ),
    ]
