# Generated by patcher – drop late_fee_accrued column
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0023_notification'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'axis_saas_feerecord'
                        AND column_name = 'late_fee_accrued'
                    ) THEN
                        ALTER TABLE axis_saas_feerecord DROP COLUMN late_fee_accrued;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE axis_saas_feerecord ADD COLUMN late_fee_accrued numeric(10,2) DEFAULT 0.00 NOT NULL;"
        ),
    ]
