# Generated by patcher – drop late_fee_accrued column (safe version)
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0023_notification'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE axis_saas_feerecord DROP COLUMN IF EXISTS late_fee_accrued;",
            reverse_sql="ALTER TABLE axis_saas_feerecord ADD COLUMN late_fee_accrued numeric(10,2) DEFAULT 0.00 NOT NULL;"
        ),
    ]
