# Generated by Django 6.0.5 on 2026-07-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0024_drop_late_fee_accrued'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclient',
            name='admin_password_hash',
            field=models.CharField(blank=True, help_text='Hashed password for admin login', max_length=128, null=True),
        ),
    ]
