# Generated by fee_fix_patcher
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0025_add_password_hash'),  # adjust to the latest migration
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='late_fee_accrued',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Accumulated late fee amount', max_digits=10),
        ),
    ]
